-- Active: 1709707512010@@127.0.0.1@5432@abtahihasan

SELECT * FROM user2

ALTER TABLE user2
ADD COLUMN success BOOLEAN DEFAULT true NOT NULL

ALTER TABLE user2
RENAME COLUMN success TO completed


ALTER TABLE user2
ALTER COLUMN email TYPE TEXT

ALTER TABLE user2
ALTER COLUMN age SET NOT NULL

ALTER TABLE user2
ALTER COLUMN age DROP NOT NULL




ALTER TABLE USER2
DROP COLUMN GENDER


ALTER TABLE USER2
ADD COLUMN BIO TEXT


ALTER TABLE USER2
DROP COLUMN BIO


ALTER TABLE USER2
ADD CONSTRAINT unique_table_email UNIQUE(email)

ALTER TABLE USER2
ALTER COLUMN EMAIL TYPE VARCHAR(30)


ALTER TABLE USER2
DROP CONSTRAINT unique_table_email

TRUNCATE TABLE USER2