-- Active: 1709707512010@@127.0.0.1@5432@abtahihasan
SELECT AVG(age) FROM STUDENTS
    GROUP BY country
        HAVING AVG(age) > 22;




SELECT EXTRACT(YEAR FROM  dob), COUNT(*) FROM STUDENTS
    GROUP BY EXTRACT(YEAR FROM  dob)

SELECT * FROM STUDENTS
